# Generated by Django 4.1.2 on 2022-10-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comment_date_time_comment_post_comment_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='choice',
            field=models.CharField(choices=[('news', 'Новости'), ('articles', 'Статьи')], default='news', max_length=10),
        ),
    ]
