# Generated by Django 4.1.2 on 2022-10-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
