# Generated by Django 4.1.2 on 2022-10-21 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='text'),
        ),
    ]
