# Generated by Django 4.1.2 on 2022-10-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_comment_comment_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='author',
            name='rating',
        ),
        migrations.AddField(
            model_name='author',
            name='author_rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
