# Generated by Django 4.1.2 on 2022-10-23 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_rename_user_author_author_remove_author_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='author',
            name='author_rating',
        ),
        migrations.AddField(
            model_name='author',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='post',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='news.post'),
        ),
    ]
