# Generated by Django 4.1.2 on 2022-10-23 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_rename_author_author_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='post',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='news.post'),
        ),
    ]
