# Generated by Django 4.1.2 on 2022-10-24 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_postcategory_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.post'),
        ),
    ]
